apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: loadubfy9035-tenant-component
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: loadubfy9035-tenant-component
    app.kubernetes.io/part-of: loadubfy9035-tenant-app
  name: loadubfy9035-tenant-component
  namespace: loadubfy9035-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: loadubfy9035-tenant-component
    weight: null
status: {}
